name: GINGERBYDESIGN
favicon: null
layout_spectrum: 0.17759
typography_spectrum: 1
title: GINGER by DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2e'
    - '#d43638'
    - '#d3aa52'
    - '#d46b4b'
    - '#5c6d86'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
